### ISSUE TITLE
Rewrite RocketMQSink with the latest 1.7.0 Flume update

### ISSUE THREAD

**Issue by shroman** [rocketmq/rocketmq-flume-ng#4]

**Comment by zhaoqun1021** [comment]
We will provide support for Flume 1.7.0 very soon

**Comment by shroman** [comment]
Hi @zhaoqun1021 
Does it mean you are already working on this issue? Or is it open for contributions?

I have started rewriting the sink, and can complete it by next week. But if you are already working on it, I stop working on it.

**Comment by zhaoqun1021** [comment]
Yes, I am working on this issue and will submit the code within the next few days.

**Comment by shroman** [comment]
Ok, I will close the issue then.
